---
title: Choose a License
description: Non-judgmental guidance on choosing a license for your open source project
relative_permalinks: false
markdown: kramdown
url: "https://choosealicense.com"

collections:
  licenses:
    output: true
    permalink: /licenses/:path/

defaults:
  -
    scope:
      path: ""
      type: "licenses"
    values:
      hidden: true
      layout: license

exclude:
  - app.coffee
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests
  - assets/vendor/clipboard/test

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript

sass:
    style: :compressed

twitter:
  username: "@github"
