---
title: ChooseALicense.com
relative_permalinks: false
markdown: kramdown
url: "http://choosealicense.com"

rules:

  required:
  - description: Include a copy of the license and copyright notice with the code.
    label: License and copyright notice
    tag: include-copyright
  - description: Indicate significant changes made to the code.
    label: State Changes
    tag: document-changes
  - description: Source code must be made available when distributing the software. In the case of LGPL, the source for the library (and not the entire program) must be made available.
    label: Disclose Source
    tag: disclose-source
  - description: The library may be used within a non-open-source application.
    label: Library usage
    tag: library-usage
  - description: You must change the name of the software if you modify it.
    label: Rename
    tag: rename

  permitted:
  - description: This software and derivatives may be used for commercial purposes.
    label: Commercial Use
    tag: commercial-use
  - description: This software may be modified.
    label: Modification
    tag: modifications
  - description: You may distribute this software.
    label: Distribution
    tag: distribution
  - description: You may grant a sublicense to modify and distribute this software to third parties not included in the license.
    label: Sublicensing
    tag: sublicense
  - description: You may use and modify the software without distributing it.
    label: Private Use
    tag: private-use
  - description: This license provides an express grant of patent rights from the contributor to the recipient.
    label: Patent Grant
    tag: patent-grant

  forbidden:
  - description: While this may be implicitly true of all licenses, this license explicitly states that you may NOT use the names, logos, or trademarks of contributors.
    label: Use Trademark
    tag: trademark-use
  - description: Software is provided without warranty and the software author/license owner cannot be held liable for damages.
    label: Hold Liable
    tag: no-liability
  - description: You may not grant a sublicense to modify and distribute this software to third parties not included in the license.
    label: Sublicensing
    tag: no-sublicense
  - description: This software may not be modified.
    label: Modification
    tag: modifications
  - description: You may not distribute this software.
    label: Distribution
    tag: distribution
  - description: You may not grant a sublicense to modify and distribute this software to third parties not included in the license.
    label: Sublicensing
    tag: sublicense

exclude:
- app.coffee
- CNAME
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- Rakefile
- README.md
- script
- bundle

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
